rails/config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects
  resources :users

end

rails/app/models/project.rb
class Project < ActiveRecord::Base
    validates :name, :presence => true
end

rails/app/models/user.rb
class User < ActiveRecord::Base
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = Project.all
    end
    def new
    end
    def create
        @project = Project.new(project_params)
        
        if @project.save
            redirect_to @project
        else
            render 'new'
        end
    end
    def show
        @project = Project.find(params[:id])
    end
    def destroy
        @project = Project.find(params[:id])
        @project.destroy
        
        redirect_to projects_path
    end
    private
        def project_params
            params.require(:project).permit(:name)
        end
end

rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
            # Login user
        else
            flash[:danger] = "Invalid email/password combination"
            render 'new'
        end
    end
    def destroy
    end
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        # Perhaps unused
    end
    def show
        @user = User.find_by_id(params[:id])
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user
        else
            flash[:danger] = "Creation failed!"
            render 'new'
        end
    end
    def new
    end
    def destroy
    end
    private
        def user_params
            params.require(:user).permit(:username,:password_digest)
        end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/project_helper.rb
module ProjectHelper
end

rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/app/helpers/users_helper.rb
module UsersHelper
end

rails/app/views/layouts/_header.html.erb
<div class="header">
    <p class="headertext">
        TO-DO LIST
    </p>
</div>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackTJ 2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container" style="margin-top:10px;margin-bottom:10px">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <% if Rails.env.development? %>
      <hr>
      <div class="container">
        <%= debug(params) %>
      </div>
    <% end %>
</body>
</html>

rails/app/views/projects/index.html.erb
<% @projects.each do |p| %>
    <div class="project">
        <p class="lead">
            <%= p.name %>
        </p>
        <%= link_to 'Show', project_path(p), {:class => "btn btn-primary"} %>
        <br>
    </div>
<% end %>
<%= link_to "New project", new_project_path, {:class => "btn btn-primary"} %>

rails/app/views/projects/new.html.erb
<%= form_for :project, url: projects_path do |f| %>
    <% if @project %>
        <span class="error_msgs">
            <ul class="alert alert-danger">
              <% for message_error in @project.errors.full_messages %>
                <li style="margin-left:20px">
                  <%= message_error %>
                </li>
              <% end %>
            </ul>
        </span>
    <% end %>
    <p>
        <%= f.label :name %>
        <br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.submit 'Create Project', :class => "btn btn-primary" %>
    </p>
<% end %>
<%= link_to 'Back to index', projects_path, {:class => "btn btn-primary"} %>

rails/app/views/projects/show.html.erb
<p class="lead">
    Name: <%= @project.name %><br>
    ID: <%= @project.id %>
</p>
<%= link_to 'Back', projects_path, {:class => 'btn btn-xs btn-primary'} %>

rails/app/views/users/new.html.erb
<% if flash[:danger] %>
    <p style="color:red">
        <%= flash[:danger] %>
    </p>
<% end %>
<%= form_for :user, url: users_path do |f| %>
    <p>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Back', users_path %>